version: "3.8"

services:
  mysql:
    image: mysql:8.1
    restart: always
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_DATA}:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306

networks:
  washku:
